### ISSUE TITLE
The problem about drawing

### ISSUE THREAD

**Issue by laohanlin** [BorgwardtLab/SAT#1]
Hi, thank you for your contribution. This is a very good open source work. I want to know how to draw the Fig.4 (Attention visualization of SAT and the Transformer) in this paper and can you share the code, please?

**Comment by yanzhangnlp** [comment]
Hi @claying and @Pseudomanifold,

I am also wondering if you can share the code of the attention visualisation? That will be very helpful!

Best,
Yan

**Comment by claying** [comment]
Hi @laohanlin and @yanzhangnlp 

Thank you for your interest. We just added the script for model visualization. You can have a look at it:
https://github.com/BorgwardtLab/SAT#model-visualization

Best,
Dexiong
