### ISSUE TITLE
2 questions about edge attribute.

### ISSUE THREAD

**Issue by Tigerrr07** [BorgwardtLab/SAT#3]
Question1:
In a graph, `edge_attr` correspond to `edge_index`, when completing the graph we get `complete_edge_index`, I think the corresponding `edge_attr` should also change to keep the same shape. But I didn't see codes about that. Where can I find this operation or maybe this operation is unnecessary?
Question2:
when calculating the attention score in sat/layers.py line 154, 155, 
```
  if edge_attr is not None:
      attn = attn + edge_attr
```
`edge attr` just sum to the attn? I can't understand it. I think it `edge_attr` could incorporated into key and value, or even not used it, because we have already use it in khpGNN. Could tell me why?

**Comment by lobray** [comment]
Hi there, thank you for your interest! We currently don't use edge attributes in the attention calculation, edge attribute information is only incorporated via the Structure Extractor (if the GNN used in the structure extractor can support edge attributes). We call the self-attention calculation on line 131-133, and we set `edge_attr = None`, so it won't trigger the lines 154-155 that you highlighted. 

You could add `edge_attr` to the attention score, e.g. as is done in [Self-Attention with Relative Position Representations](https://arxiv.org/pdf/1803.02155.pdf), but as you said you would need to have edge attributes for the complete edge index, and our method isn't currently doing that.

**Comment by Tigerrr07** [comment]
> Hi there, thank you for your interest! We currently don't use edge attributes in the attention calculation, edge attribute information is only incorporated via the Structure Extractor (if the GNN used in the structure extractor can support edge attributes). We call the self-attention calculation on line 131-133, and we set `edge_attr = None`, so it won't trigger the lines 154-155 that you highlighted.
> 
> You could add `edge_attr` to the attention score, e.g. as is done in [Self-Attention with Relative Position Representations](https://arxiv.org/pdf/1803.02155.pdf), but as you said you would need to have edge attributes for the complete edge index, and our method isn't currently doing that.

I get it. Thank you for your reply!
