### ISSUE TITLE
Question about in_embed and edge_embed.

### ISSUE THREAD

**Issue by CrescentRosexx** [BorgwardtLab/SAT#4]
Question:
In  class `GraphTransformer(nn.Module)` in sat/models.py, `in_embed=True, edge_embed=True,` so that the following code will be excuted:
```
self.embedding = nn.Embedding(in_size, d_model)
self.embedding_edge = nn.Embedding(num_edge_features, edge_dim)
```
Why should the size of the dictionary of embeddings be set to the number of input features?  I am a bit confused, after doing absolutely position encoding, why do we need this Embedding

**Comment by claying** [comment]
Hi @CrescentRosexx 

As the absolute positional embedding is added to the input node attributes, we will need an embedding layer to transform the node attributes to a vector of dimension d_model, the same dimension as the positional embedding.

**Comment by CrescentRosexx** [comment]
> Hi @CrescentRosexx
> 
> As the absolute positional embedding is added to the input node attributes, we will need an embedding layer to transform the node attributes to a vector of dimension d_model, the same dimension as the positional embedding.
I got it. Thank you for your reply!!
